from app.models.departement import Departement
from app.models.filiere import Filiere
from app.models.annee_diplomation import AnneeDiplomation
from app.models.etudiant import Etudiant
from app.models.admin import Admin
from app.models.directeur import Directeur
from app.models.chef_service import ChefServiceScolarite
from app.models.chef_bureau import ChefBureauDiplomation
from app.models.representant import RepresentantFiliere
from app.models.communique import Communique
from app.models.dossier_diplomation import DossierDiplomation
from app.models.dossier_formalisation import DossierFormalisation
from app.models.dossier_integration import DossierIntegration
from app.models.document_requis import DocumentRequis
from app.models.historique_phases import HistoriquePhases
